### ISSUE TITLE
Do not call systemctl from script in service file

### ISSUE THREAD

**Issue by phlogistonjohn** [gluster/gluster-containers#101]
PR #100 added a nice script to check for the status of /var/lib/glusterfs, however @raghavendra-talur and I were discussing this change and realized that we should not be calling systemctl from within the script. I have seen doing this lead to systemctl blocking. It would be cleaner to call `kill` on the pid of the glusterd service instead. I believe this is how glusterd is terminated by systemd currently so the impact on glusterd should be the same.

**Comment by humblec** [comment]
@phlogistonjohn not sure about the systemctl blocking behaviour. Atleast in @SaravanaStorageNetwork testing its not the case. But nothing stopping us from using `kill `. Leaving for further thoughts from @SaravanaStorageNetwork.

**Comment by phlogistonjohn** [comment]
I think that using systemd various mechanisms to make one service fail if another service fails is probably the right way to go. I'm just nervous that even though it worked for you we might run into issues in other deployments...
If we can get an opinion from @raghavendra-talur that says its OK to keep this approach I'll back off (for now >:-D)

**Comment by humblec** [comment]
Closing as per previous commment.
