### ISSUE TITLE
4.1 branch is not updated with right repo

### ISSUE THREAD

**Issue by mkumatag** [gluster/gluster-containers#123]
4.1 branch Dockerfile is referring to 4.0 repo, which needs to be updated.

Cherry-pick https://github.com/gluster/gluster-containers/pull/96 to 4.1 branch.

@humblec @mcquinne

**Comment by mkumatag** [comment]
@humblec thanks

**Comment by humblec** [comment]
YW @mkumatag . Thanks for reporting the issue!

**Comment by mkumatag** [comment]
Closing this task as now proper patch has been cherry-picked. Thanks.
