### ISSUE TITLE
Ran into bug #120 on origin 3.11 - how to upgrade ?

### ISSUE THREAD

**Issue by martinbe1io** [gluster/gluster-containers#125]
Hi everybody 

Ran into the #120 bug mentioned in the forum. I used the ansible installer with 3.11 what is the best way to only upgrade glusterfs with the commited bugfix ? I dont‘t want to upgrade the whole cluster to latest 

Thx Martin.

**Comment by SaravanaStorageNetwork** [comment]
You could follow the steps mentioned here:
https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/3.11/html-single/deployment_guide/#chap-Documentation-Red_Hat_Gluster_Storage_Container_Native_with_OpenShift_Platform-Upgrade-Gluster_pods

You should leave the image name as is in your present setup (as the documentation is more of downstream specific). 

Skip cns-deploy related steps (as you have followed ansible way of installation).

**Comment by martinbe1io** [comment]
ok thank you

am I right that that's the most important section
```
# oc edit template glusterfs
	- displayName: GlusterFS container image name
	  name: IMAGE_NAME
	  required: true
	  value: rhgs3/rhgs-server-rhel7
	- displayName: GlusterFS container image version
	  name: IMAGE_VERSION
	  required: true
	  value: v3.11
```

is a change of value from v3.11 to latest the right way?

**Comment by SaravanaStorageNetwork** [comment]
> ok thank you
> 
> am I right that that's the most important section
> 
> ```
> # oc edit template glusterfs
> 	- displayName: GlusterFS container image name
> 	  name: IMAGE_NAME
> 	  required: true
> 	  value: rhgs3/rhgs-server-rhel7
> 	- displayName: GlusterFS container image version
> 	  name: IMAGE_VERSION
> 	  required: true
> 	  value: v3.11
> ```
> is a change of value from v3.11 to latest the right way?

Yes. marking it latest is fine.
In your case (upstream), IMAGE_NAME docker.io/gluster/gluster-centos
and IMAGE_VERSION as latest

**Comment by martinbe1io** [comment]
thanks everything worked as it should
