### ISSUE TITLE
NFS share with glusterfs

### ISSUE THREAD

**Issue by bakonyip95** [gluster/gluster-containers#142]
Hi,
I will used nfs server on glusterfs, but don't work me. How to configuration pods and glusterfs?
I installed in glusterfs pods the nfs-ganesha packpage and I set nfs.disabled option to off. I stop and started the volume.
But volume status is nfs server localhost and nodes is offline.
Glusterd.log file say nfs/server.so xlator is not installed. I stop rbcbind and nfs server on host node and docker centos enabled and started rbcbind and nfs-server,nfs-ganesha.
I used latest, glusterfs 4.1 image.
Please help me.
Thanks, Peter

**Comment by phlogistonjohn** [comment]
I recommend not trying to use NFS and stick with native glusterfs for containerized applications. NFS is not a typical configuration for containerized gluster and you'd be setting yourself up for a lot of work to make it happen.

**Comment by bakonyip95** [comment]
Thanks for reply,
I need it for that because a lot of client will connected volumes and They computer is windows and macos and don't mounting glusterfs only debian.
NFS supported native all operation system and they mounted own computer.
Is there any easier or harder solution to this?

**Comment by phlogistonjohn** [comment]
Interesting. I don't think many people are trying to combine the containers use-case with the NAS-style use-case. I think you'll be exploring new ground here.
Personally, I'd use Samba/SMB for clients rather than NFS on windows, but maybe that's just me.
Good luck!

**Comment by bakonyip95** [comment]
Hm... so far, I have not thought about this, but I start SMB. Do you have any guidelines for samba share in containers glusterfs?
