### ISSUE TITLE
Any plans to upgrade container images

### ISSUE THREAD

**Issue by claudio-walser** [gluster/gluster-containers#163]
Hi
I really like glusterfs but looking at the container images, I am not sure what is going on.
Looking at the registries docker and quay I am asking myself why the last push happened around one year ago, even the latest commit in this repo is only one month old.
Even worse, quay reports alot of vulnerabilities: https://quay.io/repository/gluster/gluster-centos?tab=tags

Are there any future plans for updating or will you stop provide container images at all?

I would like to see image using recent operating systems and glusterfs 6 or even 7.

Thank you and kind regards

**Comment by humblec** [comment]
@claudio-walser the `latest` image has been created from master branch and its upto date now. Somehow the auto trigger was not working. corrected it now. thanks. I am closing this issue now.

**Comment by humblec** [comment]
@claudio-walser jfyi, the security scan has also passed on the images.

**Comment by claudio-walser** [comment]
Awesome, thank you very much for the fast action taken :-)
